export const style = `
:host{--bg:var(--background-base,#f8f7f7);--fg:var(--text-base,#252525);--muted:var(--text-weak,#777);--line:var(--border-weak-base,#ddd);font:12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--fg);color-scheme:light dark;position:fixed;bottom:0;left:0;right:0;z-index:100;}
*{box-sizing:border-box}button,select{font:inherit;color:inherit}button{cursor:pointer}button:focus-visible,select:focus-visible{outline:2px solid #5b89ef;outline-offset:-2px;border-radius:5px}
.bar{height:32px;background:var(--bg);border-top:1px solid var(--line);display:flex;align-items:center;padding:0 10px;gap:4px;overflow:hidden}
.item,.settings{border:0;background:transparent;padding:5px 8px;border-radius:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;min-width:0;max-width:340px}.item:hover,.settings:hover{background:color-mix(in srgb,var(--fg) 7%,transparent)}
.project{max-width:240px}.model{max-width:330px}.spacer{flex:1}.state{color:var(--muted);white-space:nowrap;font-size:11px;display:flex;gap:6px;align-items:center}.dot{width:6px;height:6px;border-radius:100%;background:#888}.busy .dot{background:#4b9dff;box-shadow:0 0 0 3px #4b9dff20}.error .dot{background:#e26060}.waiting .dot{background:#d7a53d}
.separator{height:12px;width:1px;background:var(--line);flex:none}.number{font-variant-numeric:tabular-nums}.warn{color:#d99b27}.danger{color:#df6960}.settings{font-size:16px;flex:none;width:30px;text-align:center;padding:3px}
.panel{position:absolute;bottom:40px;right:12px;width:min(480px,calc(100vw - 24px));max-height: min(620px,80vh);overflow:auto;background:var(--bg);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 12px 40px #0002;color:var(--fg)}
.panel[hidden]{display:none}header{display:flex;align-items:center;gap:12px;margin-bottom:16px;font-weight:600}header button{margin-left:auto;border:0;background:transparent;font-size:18px;color:var(--muted)}h3{font-size:11px;color:var(--muted);margin:18px 0 9px;font-weight:500;text-transform:uppercase;letter-spacing:.05em}.row{display:flex;justify-content:space-between;gap:24px;line-height:1.65;padding:3px 0}.label{color:var(--muted);flex:none}.value{text-align:right;overflow-wrap:anywhere;min-width:0;font-variant-numeric:tabular-nums}code{font-family:ui-monospace,monospace;font-size:11px}p{line-height:1.65;color:var(--muted);font-size:11px;margin:12px 0 0}.meter{height:5px;background:color-mix(in srgb,var(--fg) 10%,transparent);border-radius:5px;margin:12px 0;overflow:hidden}.fill{height:100%;background:#5a9cf0}.check{display:flex;gap:8px;align-items:center;padding:5px 0}.action{background:transparent;border:1px solid var(--line);padding:6px 10px;border-radius:6px;margin-top:12px}.lang{background:var(--bg);border:1px solid var(--line);padding:5px;border-radius:5px}
@media(max-width:900px){.project{max-width:150px}.model{max-width:220px}.tokens{display:none}}
@media(max-width:650px){.project{display:none}.model{max-width:180px}.state span{display:none}.separator{display:none}.item{padding:5px}}
@media(max-width:430px){.speed{display:none}.model{max-width:140px}}
`
